baseURL: https://robwilliams.me
disablePathToLower: true
languageCode: en-us
title: Rob Williams
theme: hello-friend-ng
author:
  name: Rob Williams
disableRSS: false
params:
  homeSubtitle: personal blog of tech projects
  logo:
    logoText: robwilliams.me
    logoHomeLink: /
    logoCursorColor: "#afff94"
  social:
    - name: github
      url: https://github.com/robwil/
    - name: linkedin
      url: https://www.linkedin.com/pub/robert-williams/19/127/113
    - name: email
      url: "mailto:contact@robwilliams.me"
    
menu:
  main:
    - identifier: posts
      name: Posts
      url: post/
    - identifier: resume
      name: Resume
      url: https://robwilliams.me/resume/resume.pdf
